version: 0.4.{build}

branches:
  only:
  - appveyor 

clone_depth: 1

before_build:
- cmd: dir "C:\Program Files (x86)\Mono\lib\mono\4.5"
- cmd: nuget restore

build:

  project: Crow.sln

  verbosity: normal
