version: 0.4.{build}

branches:
  only:
  - appveyor 

clone_depth: 1

before_build:
- cmd: nuget restore
#- cmd: reg query hklm 

build_script:
- ps: dotnet -v --version
- cmd: build.cmd %BUILD_TARGET%

test: off

build:
  project: Crow.sln
  verbosity: normal
