version: 0.4.{build}

branches:
  only:
  - appveyor

clone_depth: 1

#before_build:
#- cmd: reg add HKLM\SOFTWARE\Microsoft\.NETFramework\v4.0.30319\SKUs\.NETFramework /v Version /t REG_SZ /d "v4.0" /f
#- cmd: reg add HKLM\SOFTWARE\Microsoft\.NETFramework\v4.0.30319\SKUs\.NETFramework /v Profile /t REG_SZ /d "Mono" /f
#- cmd: reg add HKLM\SOFTWARE\Wow6432Node\Microsoft\.NETFramework\v4.0.30319\SKUs\.NETFramework /v Version /t REG_SZ /d "v4.0" /f
#- cmd: reg add HKLM\SOFTWARE\Wow6432Node\Microsoft\.NETFramework\v4.0.30319\SKUs\.NETFramework /v Profile /t REG_SZ /d "Mono" /f
#- cmd: mklink /d "C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.0\Profile\Mono" "C:\Program Files (x86)\Mono\lib\mono\4.5"
#- cmd: mkdir "C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.0\Profile\Mono\RedistList"
#- cmd: echo "<?xml version='1.0' encoding='utf-8'?><FileList  Redist='Mono-4.5' Name='Mono 4.5 Profile' RuntimeVersion='4.5' ToolsVersion='4.0' > </FileList>" > "C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.0\Profile\Mono\RedistList\FrameworkList.xml"
#- cmd: nuget restore

#- cmd: dir "C:\Program Files (x86)\Mono\lib\mono\4.5"

build_script:
    - C:\"Program Files (x86)"\Mono\lib\mono\4.5\xbuild /p:Configuration=Release Crow.sln

build: off

#build:

#  project: Crow.sln

#  verbosity: normal
